budgets/urls.py
from django.urls import path

from budgets import views

urlpatterns = [
    path("", views.BudgetListView.as_view(), name="budget-list"),
    path("add/", views.BudgetCreateView.as_view(), name="budget-add"),
    path("<int:pk>/edit/", views.BudgetUpdateView.as_view(), name="budget-edit"),
    path(
        "<int:pk>/update-expenses/",
        views.BudgetUpdateExpensesView.as_view(),
        name="budget-update-expense",
    ),
    path(
        "<int:pk>/assignments/",
        views.BudgetAssigmentListView.as_view(),
        name="budget-assignment-list",
    ),
    path(
        "assignments/add/",
        views.BudgetAssignmentCreateView.as_view(),
        name="assignment-add",
    ),
    path(
        "assignments/<int:pk>/edit/",
        views.BudgetAssignmentUpdateView.as_view(),
        name="assignment-edit",
    ),
]

expenses/api/urls.py
# Django Imports
from django.urls import include, path

# DRF imports
from rest_framework.routers import DefaultRouter

# Model Imports
from expenses import api as api_views

router = DefaultRouter()
router.register(r"expenses", api_views.TransactionViewSet, basename="expenses")
router.register(r"accounts", api_views.AccountViewSet, basename="accounts")
router.register(
    r"currency_converts", api_views.CurrencyConvertViewSet, basename="currency_converts"
)

urlpatterns = [
    path("", include(router.urls)),
    # currencies
    path(
        "create_usd_exchange/",
        api_views.CreateDollarConversionView.as_view(),
        name="create-dollar-convert",
    ),
    path(
        "account_assoc/",
        api_views.AccountAssociationView.as_view(),
        name="account-assoc",
    ),
    path(
        "upload_file_cleanup/",
        api_views.TransactionUploadFileCleanupView.as_view(),
        name="upload-file-cleanup",
    ),
    path(
        "invalid_cleanup/",
        api_views.TransactionDeleteInvalidView.as_view(),
        name="expense-invalid-account-cleanup",
    ),
]

expenses/urls.py
# Django Imports
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

# Model Imports
from expenses import views

urlpatterns = [
    path(
        "accounts/",
        views.AccountListView.as_view(),
        name="account-list",
    ),
    path(
        "accounts/transfer/",
        views.AccountTransferView.as_view(),
        name="account-transfer",
    ),
    path(
        "currency/convert/",
        views.CurrencyConvertListView.as_view(),
        name="currency-convert-list",
    ),
    path(
        "",
        views.TransactionListView.as_view(),
        name="transaction-list",
    ),
    path(
        "add/",
        views.TransactionCreateView.as_view(),
        name="transaction-add",
    ),
    path(
        "<int:pk>/edit/",
        views.TransactionUpdateView.as_view(),
        name="transaction-edit",
    ),
    path(
        "<int:pk>/delete/",
        views.TransactionDeleteView.as_view(),
        name="transaction-delete",
    ),
    path(
        "uploads/",
        views.UploadListView.as_view(),
        name="upload-list",
    ),
    path(
        "upload/add/",
        views.UploadView.as_view(),
        name="upload-add",
    ),
    path(
        "upload/transform_credit_card/<int:pk>/",
        views.UploadTransformCreditCardView.as_view(),
        name="upload-transform-credit-card",
    ),
    path(
        "upload/transform_account/<int:pk>/",
        views.UploadTransformAccountView.as_view(),
        name="upload-transform-account",
    ),
    path(
        "upload/result/<int:pk>/",
        views.UploadResultView.as_view(),
        name="upload-result",
    ),
    path(
        "upload/inspect/<int:pk>/",
        views.UploadInspectView.as_view(),
        name="upload-inspect",
    ),
    path(
        "periods/",
        views.PeriodListView.as_view(),
        name="period-list",
    ),
    path(
        "periods/add/",
        views.PeriodCreateView.as_view(),
        name="period-add",
    ),
    path(
        "periods/<int:period>/",
        views.TransactionGroupListView.as_view(),
        name="period-expense-group",
    ),
    path(
        "periods/<int:pk>/close/",
        views.PeriodCloseView.as_view(),
        name="period-close",
    ),
    path(
        "periods/<int:pk>/open/",
        views.PeriodOpenView.as_view(),
        name="period-open",
    ),
    path(
        "remove-invalid/",
        views.TransactionRemoveInvalidView.as_view(),
        name="remove-invalid",
    ),
    path(
        "create-dollars/",
        views.CreateDollarConversionView.as_view(),
        name="create-dollars-convertion",
    ),
    path("loans/", views.LoanListView.as_view(), name="loan-list"),
    path("loans/add/", views.LoanCreateView.as_view(), name="loan-add"),
    path(
        "subscriptions/", views.SubscriptionListView.as_view(), name="subscription-list"
    ),
    path(
        "subscriptions/add/",
        views.SubscriptionCreateView.as_view(),
        name="subscription-add",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expenses_site/urls.py
from django.contrib import admin
from django.urls import include, path

from expenses.views.home import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("expenses/", include("expenses.urls")),
    path("budgets/", include("budgets.urls")),
    path("api/expenses/", include("expenses.api.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

expenses/models.py
from datetime import timedelta
from decimal import Decimal

from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.db import models
from django.db.models import F
from django.db.models.functions import Abs
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from expenses.mixins import CreationModificationDateMixin


class Period(models.Model):
    month = models.IntegerField(_("Mes"))
    year = models.IntegerField(_("Año"))
    closed = models.BooleanField(_("Solo lectura"), default=False)
    total = models.DecimalField(
        _("Monto total"), max_digits=13, decimal_places=2, default=0
    )
    active = models.BooleanField(_("Es visible"), default=True)

    class Meta:
        verbose_name = _("Periodo")
        verbose_name_plural = _("Periodos")
        unique_together = ("month", "year")

    def __str__(self) -> str:
        return f"{self.year}-{self.month:02}"

    @staticmethod
    def get_period_from_date(payment_date):
        try:
            return Period.objects.get(year=payment_date.year, month=payment_date.month)
        except Period.DoesNotExist:
            return None


class Currency(models.Model):
    name = models.CharField(_("Nombre"), max_length=100)
    alpha3 = models.CharField(_("Codigo alpha-3"), max_length=3, blank=True, null=True)

    class Meta:
        verbose_name = _("Moneda")
        verbose_name_plural = _("Monedas")

    def __str__(self) -> str:
        return self.name


class CurrencyConvert(models.Model):
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    exchange = models.DecimalField(
        _("Tasa de conversión"), max_digits=10, decimal_places=4
    )
    date = models.DateField(_("Fecha de conversión"), auto_now_add=True)

    class Meta:
        verbose_name = _("Conversion de moneda")
        verbose_name_plural = _("Conversiones de monedas")

    def __str__(self) -> str:
        return f"{self.date} > {self.currency}"


class Account(models.Model):
    DEBE = -1
    HABER = 1
    SIGN_TYPE = (
        (DEBE, "Debe (-)"),
        (HABER, "Haber (+)"),
    )
    FIXED = "FIX"
    VARIABLE = "VAR"
    ACCOUNT_TYPE = (
        (FIXED, "Fijo"),
        (VARIABLE, "Variable"),
    )
    name = models.CharField(_("Nombre"), max_length=100)
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    sign = models.IntegerField(_("Signo"), choices=SIGN_TYPE)
    account_type = models.CharField(
        _("Tipo de cuenta"), max_length=5, choices=ACCOUNT_TYPE, default=VARIABLE
    )

    class Meta:
        verbose_name = _("Cuenta")
        verbose_name_plural = _("Cuentas")

    def __str__(self) -> str:
        _sign = "-" if self.sign == -1 else "+"
        p_name = f" < {self.parent.name}" if self.parent else ""
        return f"{self.name} {p_name} [{_sign}{self.account_type}]"


class Accountable(CreationModificationDateMixin):
    period = models.ForeignKey(Period, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    amount = models.DecimalField(_("Monto"), max_digits=13, decimal_places=2)

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return f"{self.period} => {self.account}: {self.currency.alpha3} {self.amount}"

    @property
    def amount_str(self):
        return f"{self.currency.alpha3} {self.amount}"

    @property
    def get_signed_value(self) -> float:
        return self.amount * self.account.sign


def expense_upload_path(instance, filename):
    now = timezone.now()
    return f"expenses/{now.strftime('%Y/%m')}/{filename}"


def upload_dimension_default():
    return {
        "rows": 0,
        "cols": 0,
    }


def upload_parameters_default():
    return {
        "rows": {
            "start": 0,
            "end": 0,
        },
        "cols": [],
    }


class Upload(CreationModificationDateMixin):
    file = models.FileField(
        _("Archivo"), blank=True, null=True, upload_to=expense_upload_path
    )
    data = models.JSONField(_("Datos"), blank=True, null=True)
    dimension = models.JSONField(
        _("Dimension del document"), default=upload_dimension_default
    )
    result = models.JSONField(_("Resultado"), blank=True, null=True)
    parameters = models.JSONField(
        _("Parámetros"), blank=True, null=True, default=upload_parameters_default
    )
    start_date = models.DateField(
        _("Fecha de inicio"), default=timezone.now, blank=True, null=True
    )
    end_date = models.DateField(
        _("Fecha de fin"), default=timezone.now, blank=True, null=True
    )

    class Meta:
        verbose_name = _("Subida de archivo")
        verbose_name_plural = _("Subidas de archivos")

    def __str__(self) -> str:
        return str(self.file.name)


class UploadData(models.Model):
    upload = models.ForeignKey(Upload, on_delete=models.CASCADE)
    json = models.JSONField()


class Transaction(Accountable):
    description = models.CharField(
        _("Descripción"), max_length=255, blank=True, null=True
    )
    payment_date = models.DateField(
        _("Fecha de pago"), default=timezone.now, blank=True, null=True
    )
    local_amount = models.DecimalField(
        _("Monto local"), max_digits=13, decimal_places=2, default=0, editable=False
    )
    identifier = models.CharField(max_length=64, blank=True, null=True)
    upload = models.ForeignKey(
        Upload,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = _("Transacción")
        verbose_name_plural = _("Transacciones")

    def __str__(self) -> str:
        return super().__str__()

    @property
    def get_local_amount(self) -> Decimal:
        data = (
            CurrencyConvert.objects.filter(
                currency=self.currency,
                date__lte=self.payment_date
                + timedelta(days=settings.CURRENCY_CONVERT_DAYS_RANGE),
                date__gte=self.payment_date
                - timedelta(days=settings.CURRENCY_CONVERT_DAYS_RANGE),
            )
            .annotate(date_difference=Abs(F("date") - self.payment_date))
            .order_by("date_difference")
            .values("exchange")[:1]
        )
        exchange = data[0]["exchange"] if data else 1
        return Decimal(self.amount) * Decimal(self.account.sign) * Decimal(exchange)

    def save(self, *args, **kwargs):
        self.local_amount = self.get_local_amount
        super().save(*args, **kwargs)


class ProgramTransaction(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    amount = models.DecimalField(_("Monto"), max_digits=13, decimal_places=2)
    name = models.CharField(_("Nombre"), max_length=100)
    start_date = models.DateField(
        _("Fecha de inicio"), default=timezone.now, blank=True, null=True
    )
    end_date = models.DateField(
        _("Fecha de fin"), default=timezone.now, blank=True, null=True
    )
    active = models.BooleanField(_("Programado"), default=True)

    class Meta:
        verbose_name = _("Transacción programada")
        verbose_name_plural = _("Transacciones programadas")

    def __str__(self) -> str:
        return f"{self.name}"


class AccountAsociation(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    token = models.CharField(_("Token para asociar"), max_length=100)

    class Meta:
        verbose_name = _("Asociacion de cuenta")
        verbose_name_plural = _("Asociaciones de cuentas")

    def __str__(self) -> str:
        return f"{self.account.name} -> {self.token}"


class Loan(models.Model):
    description = models.CharField(_("Descripción"), max_length=255)
    amount = models.DecimalField(_("Monto"), max_digits=13, decimal_places=2)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)
    start_date = models.DateField(
        _("Fecha de inicio"), default=timezone.now, blank=True, null=True
    )
    monthly_payment = models.DecimalField(
        _("Pago mensual"), max_digits=13, decimal_places=2
    )
    months = models.SmallIntegerField(_("Meses"), default=0)
    is_active = models.BooleanField(_("Activo"), default=True)
    bank = models.CharField(_("Banco"), max_length=100)

    class Meta:
        verbose_name = _("Préstamo")
        verbose_name_plural = _("Préstamos")

    def __str__(self) -> str:
        return f"{self.bank} - {self.description} ({self.monthly_payment})"

    @property
    def end_date(self):
        return self.start_date + relativedelta(months=self.months)

    @property
    def percentage(self):
        start_date = self.start_date
        end_date = self.end_date
        if start_date > end_date:
            start_date, end_date = (
                end_date,
                start_date,
            )  # Ensure start_date is before end_date

        total_months = (end_date - start_date).days
        months_elapsed = (timezone.now().date() - start_date).days
        return min(round(months_elapsed * 100.0 / total_months), 100)

    @property
    def get_local_monthly_payment(self):
        currency_convert = (
            CurrencyConvert.objects.filter(
                currency=self.currency,
            )
            .order_by("-date")
            .only("exchange")
            .first()
        )
        exchange = currency_convert.exchange if currency_convert else Decimal(1)
        return self.monthly_payment * exchange

    @staticmethod
    def get_future_payments(date_after):
        if date_after is None:
            return 0

        active_loans = Loan.objects.filter(is_active=True)
        total_payment = Decimal(0)
        for loan in active_loans:
            if loan.end_date < date_after:
                continue

            currency_convert = (

expenses/views/accounts.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.edit import FormView

from expenses.forms import AccountTransferForm
from expenses.models import Account, AccountAsociation, Transaction


class AccountListView(ListView):
    model = Account
    template_name = "expenses/account_list.html"
    context_object_name = "accounts"
    ordering = ["-sign", "name"]


class AccountTransferView(FormView):
    template_name = "expenses/account_transfer.html"
    form_class = AccountTransferForm

    def get_success_url(self) -> str:
        return reverse("account-list")

    def form_valid(self, form):
        account_origin = form.cleaned_data["account_origin"]
        account_destination = form.cleaned_data["account_destination"]

        # change expenses from account_origin to account_destination
        Transaction.objects.filter(account=account_origin).update(
            account=account_destination
        )

        AccountAsociation.objects.filter(account=account_origin).update(
            account=account_destination
        )

        account_origin.delete()

        return HttpResponseRedirect(self.get_success_url())

expenses/views/currencies.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from rest_framework.views import APIView

from expenses.models import CurrencyConvert


class CurrencyConvertListView(ListView):
    model = CurrencyConvert
    template_name = "expenses/currency_convert_list.html"
    context_object_name = "currency_converts"
    ordering = ["-date"]


class CreateDollarConversionView(APIView):
    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse_lazy("currency-convert-list"))

expenses/views/home.py
from django.shortcuts import redirect
from django.views import View


class HomeView(View):
    def get(self, request, *args, **kwargs):
        return redirect("period-list")

templates/expenses/currency_convert_list.html
{% extends 'base.html' %}

{% block title %}
Currency Conversion
{% endblock %}

{% block content %}
<div class="col-md-6">
    <h1>Currency Conversion List</h1>
    <table class="table table-striped">
        <tr>
            <th>Currency</th>
            <th>Exchange</th>
            <th>Date</th>
        </tr>
        {% for item in currency_converts %}
        <tr>
            <td>{{ item.currency }}</td>
            <td>{{ item.exchange }}</td>
            <td>{{ item.date }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/expenses/expense_upload_result.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
Expense Upload Result
{% endblock %}

{% block content %}
<div class="col-md-8">
    <h1>Expense Upload Result</h1>
    <p>Expenses created {{ summary.created }} of {{ summary.total }}</p>
    <p>File upload: <code>{{ file }}</code></p>
    <table class="table table-striped">
        <tr>
            <th class="text-center">Line number</th>
            <th>Row</th>
            <th>Description</th>
        </tr>
        {% for line_number, value in result.items %}
        <tr>
            <td class="text-center">{{ line_number }}</td>
            <td><pre>{{ value.source }}</pre></td>
            <td>
                {% if value.description == "CREATED" %}
                <span class="badge text-bg-success rounded-pill">{{ value.description }}</span>
                {% elif value.description == "Expense already exists" %}
                <span class="badge text-bg-danger rounded-pill">{{ value.description }}</span>
                {% else %}
                <span class="badge text-bg-warning rounded-pill">{{ value.description }}</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/expenses/loan_add.html
{% extends 'base.html' %}

{% block title %}
Loans
{%endblock %}

{% block content %}
  <h1>New Loan</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/expenses/subscription_list.html
{% extends 'base.html' %} {% load humanize %}

{% block title %}
Subscriptions
{%endblock %}

{% block content %}
<div class="col-md-8">
  <h1>Subscriptions</h1>
  <div class="card" style="width: 18rem">
    <div class="card-body">
      <h4 class="card-text">Total: {{ total|floatformat:"2"|intcomma }}</h4>
    </div>
  </div>
  <br />
  <p><a href="{% url 'subscription-add' %}">Add</a></p>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th class="text-end">Payment (month)</th>
      <th class="text-center">Active</th>
    </tr>
    {% for subscription in subscriptions %}
    <tr>
      <td>{{ subscription.name }}</td>
      <td>{{ subscription.subscription_type }}</td>
      <td class="text-end">{{ subscription.currency.alpha3 }} {{ subscription.monthly_payment|floatformat:"2"|intcomma }}</td>
      <td class="text-center">
        {% if subscription.is_active %}
        <i class="btn btn-success fa fa-check" aria-hidden="true"></i>
        {% else %}
        <i class="btn btn-danger fa fa-times" aria-hidden="true"></i>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

templates/expenses/transaction_add.html
{% extends 'base.html' %}

{% block title %}
Transactions
{%endblock %}

{% block content %}
  <h2>Create/Edit Transaction</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/expenses/transaction_group.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
Transactions
{% endblock %}

{% block content %}
<div class="col-md-6">
    <h1>Transactions by Account</h1>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h2 class="card-title">{{ period }}</h2>
            <h4 class="card-text">Local Total: {{ total|floatformat:"2"|intcomma }}</h4>
            <p class="card-text">Last date: {{ last_trx }}</p>
        </div>
    </div>
    <table class="table table-striped" style="margin-top: 10px;">
        <tr>
            <th>Account</th>
            <th class="text-end">Amount</th>
        </tr>
        {% for group in expenses %}
        <tr>
            <td><a href="{% url 'transaction-list' %}?period={{ period_id }}&account={{ group.account__id }}">{{ group.account__name }}</a></td>
            <td class="text-end {% if group.total >= 0 %}text-bg-success{% else %}text-bg-danger{% endif %}" scope="col">{{ group.total|floatformat:"2"|intcomma }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/expenses/transaction_list.html
{% extends 'base.html' %}
{% load humanize query_params %}

{% block title %}
Transactions
{%endblock %}

{% block content %}
<h1>Transaction List</h1>
<p><a href="{% url 'transaction-add' %}">Add</a> | <a href="{% url 'upload-add' %}">Upload</a></p>
<table class="table table-striped">
    <tr>
        <th>Period</th>
        <th>Account</th>
        <th class="text-end">Amount</th>
        <th>Description</th>
        <th>Payment date</th>
    </tr>
    {% for expense in expenses %}
    <tr>
        <td>{{ expense.period }}</td>
        <td>{{ expense.account.name }}</td>
        <td class="text-end {% if expense.account.sign == 1 %}text-bg-success{% else %}text-bg-danger{% endif %}"
            scope="col">
            {{ expense.local_amount|floatformat:"2"|intcomma }}
        </td>
        <td>{{ expense.description }}</td>
        <td>{{ expense.payment_date }}</td>
    </tr>
    {% endfor %}
</table>
<!--paginator-->
<nav aria-label="Page navigation expense">
    <ul class="pagination">
        {% if expenses.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?{% query_transform page=1 %}">&laquo; first</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?{% query_transform page=expenses.previous_page_number %}">Previous</a>
        </li>
        {% endif %}
        <li class="page-item">
            <span class="current page-link">
                Page {{ expenses.number }} of {{ expenses.paginator.num_pages }}.
            </span>
        </li>
        {% if expenses.has_next %}
        <li class="page-item">
            <a class="page-link" href="?{% query_transform page=expenses.next_page_number %}">Next</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?{% query_transform page=expenses.paginator.num_pages %}">last &raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

templates/expenses/transaction_upload_result.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
Expense Upload Result
{% endblock %}

{% block content %}
<div class="col-md-8">
    <h1>Expense Upload Result</h1>
    <p>Expenses created {{ summary.created }} of {{ summary.total }}</p>
    <p>File upload: <code>{{ upload.file }}</code></p>
    <hr>
    <p><a href="{% url 'transaction-upload-inspection' pk=upload.pk %}">Inspect transactions uploaded</a></p>
    <table class="table table-striped">
        <tr>
            <th class="text-center">Line number</th>
            <th>Row</th>
            <th>Description</th>
        </tr>
        {% for line_number, value in result.items %}
        <tr>
            <td class="text-center">{{ line_number }}</td>
            <td><pre>{{ value.source }}</pre></td>
            <td>
                {% if value.description == "CREATED" %}
                <span class="badge text-bg-success rounded-pill">{{ value.description }}</span>
                {% elif value.description == "Expense already exists" %}
                <span class="badge text-bg-danger rounded-pill">{{ value.description }}</span>
                {% else %}
                <span class="badge text-bg-warning rounded-pill">{{ value.description }}</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/expenses/upload.html
{% extends 'base.html' %}

{% block title %}
File expense upload
{% endblock %}

{% block content %}
<div class="col-md-6">
    <h1>File upload</h1>
    <p>The columns of the CSV file are:</p>
    <pre class="bg-light text-dark">Payment date, description, amount(with currency), account</pre>
    <p>The amount actually are:</p>
    <ul>
        <li>HNL: Lempiras (predetermined)</li>
        <li>USD: Dollars</li>
    </ul>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3 row">
            <label for="id_file" class="col-sm-4 col-form-label">File:</label>
            <div class="col-sm-8">
                {{ form.file }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary mb-3">Enviar</button>
    </form>
    {% if field.errors %}
    <div class="errors">
        {% for error in field.errors %}
        <div class="fieldError">
            {{ error }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

templates/expenses/upload_add.html
{% extends 'base.html' %}

{% block title %}
File upload
{% endblock %}

{% block content %}
<div class="col-md-6">
    <h1>File upload</h1>
    <p>The columns of the CSV file are:</p>
    <pre class="bg-light text-dark">Payment date, description, amount(with currency), account</pre>
    <p>The amount actually are:</p>
    <ul>
        <li>HNL: Lempiras (predetermined)</li>
        <li>USD: Dollars</li>
    </ul>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3 row">
            <label for="id_file" class="col-sm-4 col-form-label">File:</label>
            <div class="col-sm-8">
                {{ form.file }}
            </div>
        </div>
        <div class="mb-3 row">
            <label for="id_type" class="col-sm-4 col-form-label">Type:</label>
            <div class="col-sm-8">
                {{ form.file_type }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary mb-3">Enviar</button>
    </form>
    {% if field.errors %}
    <div class="errors">
        {% for error in field.errors %}
        <div class="fieldError">
            {{ error }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

templates/expenses/upload_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
Upload List
{% endblock %}

{% block stylesheets %}
<style>
    .btn {
        width: 60px;
    }
</style>
{% endblock %}

{% block content %}
<div class="col-md-12">
    <h1>Uploads</h1>
    <p><a href="{% url 'upload-add' %}">Add</a></p>
    <table class="table table-striped">
        <tr>
            <th>Created</th>
            <th>File</th>
            <th>Transactions</th>
            <th>Results</th>
        </tr>
        {% for upload in uploads %}
        <tr>
            <td>{{ upload.created }}</td>
            <td>{{ upload.file.name }}</td>
            <td>
                <a href="{% url 'transaction-list' %}?upload={{ upload.id }}" class="btn btn-success">{{ upload.trx_count }}</a>
            </td>
            <td>
                <a href="{% url 'upload-result' pk=upload.pk %}" class="btn btn-primary">{{ upload.line_count }}</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}